# Generated by Django 3.0.5 on 2020-04-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('original_link', models.CharField(max_length=200)),
                ('images', models.CharField(max_length=200)),
                ('screen1', models.CharField(max_length=200)),
                ('screen2', models.CharField(max_length=200)),
                ('screen3', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('release', models.DateField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
            ],
        ),
    ]
